#! /bin/bash
sudo yum install xfsprogs -y
sudo mkfs -t xfs /dev/nvme1n1
sudo mkfs -t xfs /dev/nvme2n1
cd /var
sudo mkdir www
cd /home/ec2-user/
sudo -u ec2-user mkdir mysql-server
sudo mount /dev/nvme1n1 /home/ec2-user/mysql-server
sudo mount /dev/nvme2n1 /var/www
sudo echo $(blkid | grep /dev/nvme1n1 | awk '{print $2}') /home/ec2-user/mysql-server/ xfs defaults 1 1 >> /etc/fstab
sudo echo $(blkid | grep /dev/nvme2n1 | awk '{print $2}') /var/www xfs defaults 1 1 >> /etc/fstab
sudo mount -a
cd mysql-server
sudo wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
sudo rpm -Uvh mysql80-community-release-el9-1.noarch.rpm
sudo yum install mysql-community-{server,client,client-plugins,icu-data-files,common,libs}-* -y
sudo systemctl start mysqld
sudo mysql -e "CREATE USER 'wordpress-user'@'localhost' IDENTIFIED BY 'Mysql123$';"
sudo mysql -e "CREATE DATABASE `wordpress-db`;"
sudo mysql -e "GRANT ALL PRIVILEGES ON `wordpress-db`.* TO \"wordpress-user\"@\"localhost\";"
sudo mysql -e "FLUSH PRIVILEGES;"
sudo systemctl stop mysqld
sudo systemctl start mysqld
sudo yum install nginx -y
sudo systemctl start nginx
sudo chkconfig nginx on
cd ..
sudo aws s3 cp s3://viobuck/nginx.conf /etc/nginx/nginx.conf
cd /var/www
sudo wget https://wordpress.org/latest.tar.gz
sudo tar -xzf latest.tar.gz
sudo aws s3 cp s3://viobuck/wp-config.php /var/www/wordpress/wp-config.php
