#! /bin/bash
sudo yum install xfsprogs -y
sudo mkfs -t xfs /dev/nvme1n1
sudo mkdir mysql-server
sudo mount /dev/nvme1n1 ./mysql-server
echo $(blkid | grep /dev/nvme1n1 | awk '{print $2}') /home/ec2-user/mysql-server/ xfs defaults 1 1 >> /etc/fstab
sudo mount -a
